title: Project

fields:
    description:
        type: text
        label: Descriptoion
    employees:
      type: manytomany
      label: Employees
      fields:
        foreignkey:
          label: Employee
          type: select
          options: query
          query:
            fetch: site.childrenanddrafts.template('employee')
            text: "{{ page.title }}"
            value: "{{ page.uuid }}"
        hours:
          type: number
          label: Number of hours
      validate:
        unique: employees
      relatationField: projects